import assert from 'node:assert/strict';
const root='projects/demo-kubias/databases/(default)/documents',base='http://127.0.0.1:8080/v1/'+root;
const token=uid=>[Buffer.from(JSON.stringify({alg:'none',typ:'JWT'})).toString('base64url'),Buffer.from(JSON.stringify({iss:'https://securetoken.google.com/demo-kubias',aud:'demo-kubias',sub:uid,user_id:uid,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+3600,firebase:{sign_in_provider:'anonymous'}})).toString('base64url'),''].join('.');
const fields=data=>Object.fromEntries(Object.entries(data).map(([k,v])=>[k,typeof v==='string'?{stringValue:v}:typeof v==='boolean'?{booleanValue:v}:{integerValue:String(v)}]));
const call=(path,method,body,auth)=>fetch(base+path,{method,headers:{'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+auth}:{})},body:body?JSON.stringify(body):undefined});
const set=(path,data)=>({update:{name:root+'/'+path,fields:fields(data)},updateTransforms:[{fieldPath:'updatedAt',setToServerValue:'REQUEST_TIME'}]});
let passed=0;async function check(label,promise,ok){const r=await promise,body=await r.text();assert.equal(r.ok,ok,label+': '+r.status+' '+body);passed++;console.log('PASS '+label);}
const commit=(writes,uid)=>call(':commit','POST',{writes},uid?token(uid):undefined);
const reset=await fetch('http://127.0.0.1:8080/emulator/v1/projects/demo-kubias/databases/(default)/documents',{method:'DELETE'});assert.ok(reset.ok);
const stream={title:'Test',description:'Story',category:'RedM',art:'ROLEPLAY',theme:'rp',platform:'twitch',start:Date.now()+7200000,end:Date.now()+18000000,status:'confirmed',visibility:'published',liveUntil:0,change:'',version:1};
await check('seed stream',call('/streams/a','PATCH',{fields:fields(stream)},'owner'),true);
await call('/streams/draft','PATCH',{fields:fields({...stream,visibility:'draft'})},'owner');
const writes=(uid,choice,counts,id='a')=>[choice?set('visitors/'+uid+'/votes/'+id,{choice}):{delete:root+'/visitors/'+uid+'/votes/'+id},set('streams/'+id+'/stats/reactions',counts),set('visitors/'+uid,{})];
const cool=uid=>call('/visitors/'+uid,'PATCH',{fields:{updatedAt:{timestampValue:'2020-01-01T00:00:00Z'}}},'owner');
await check('unauthenticated write denied',commit(writes('one','going',{going:1,maybe:0,unavailable:0})),false);
await check('first atomic vote',commit(writes('one','going',{going:1,maybe:0,unavailable:0}),'one'),true);
await check('public totals readable',call('/streams/a/stats/reactions','GET'),true);
await check('private vote not public',call('/visitors/one/votes/a','GET'),false);
await check('other identity cannot read vote',call('/visitors/one/votes/a','GET',null,token('two')),false);
await check('owner reads own vote',call('/visitors/one/votes/a','GET',null,token('one')),true);
await check('immediate change denied',commit(writes('one','maybe',{going:0,maybe:1,unavailable:0}),'one'),false);
await cool('one');
await check('same vote replay denied',commit(writes('one','going',{going:2,maybe:0,unavailable:0}),'one'),false);
await check('forged totals denied',commit(writes('one','maybe',{going:100,maybe:100,unavailable:0}),'one'),false);
await check('total alone denied',commit([set('streams/a/stats/reactions',{going:2,maybe:0,unavailable:0})],'one'),false);
await check('vote alone denied',commit([set('visitors/one/votes/a',{choice:'maybe'})],'one'),false);
await check('second viewer adds',commit(writes('two','going',{going:2,maybe:0,unavailable:0}),'two'),true);
await check('switch keeps total consistent',commit(writes('one','maybe',{going:1,maybe:1,unavailable:0}),'one'),true);
await cool('one');
await check('deletion adjusts totals',commit(writes('one',null,{going:1,maybe:0,unavailable:0}),'one'),true);
await check('delete recreate cooldown enforced',commit(writes('one','going',{going:2,maybe:0,unavailable:0}),'one'),false);
await check('guard deletion denied',call('/visitors/one','DELETE',null,token('one')),false);
await check('forge someone else vote denied',commit(writes('two','maybe',{going:0,maybe:1,unavailable:0}),'one'),false);
await cool('one');
await check('draft vote denied',commit(writes('one','going',{going:1,maybe:0,unavailable:0},'draft'),'one'),false);
await call('/streams/a','PATCH',{fields:fields({...stream,status:'cancelled'})},'owner');
await check('cancelled vote denied',commit(writes('one','going',{going:2,maybe:0,unavailable:0}),'one'),false);
await cool('two');
await check('withdraw from cancelled stream',commit(writes('two',null,{going:0,maybe:0,unavailable:0}),'two'),true);
await call('/streams/a','PATCH',{fields:fields({...stream,start:Date.now()-1000})},'owner');
await check('past start vote denied',commit(writes('one','going',{going:1,maybe:0,unavailable:0}),'one'),false);
await call('/streams/a','PATCH',{fields:fields(stream)},'owner');
await cool('one');await check('new vote after delay',commit(writes('one','going',{going:1,maybe:0,unavailable:0}),'one'),true);
await call('/streams/a','DELETE',null,'owner');await cool('one');
await check('withdraw after stream deleted',commit(writes('one',null,{going:0,maybe:0,unavailable:0}),'one'),true);
console.log(passed+' reaction security checks passed');
